"""CodeAgent-X package."""

from .agent import (
    AgentLoop,
    PlanRepair,
    PlanStepKind,
    RunBudget,
    TrajectoryRecorder,
    build_plan_repair,
    build_runtime_plan,
)
from .agent.guidance import ToolGuidanceCheck, ToolGuidanceStatus, ToolPlanningGuidance
from .agent.state import AgentState, TaskStatus
from .context_engine import AstContextManager, ContextCandidate, ContextRanker
from .context_engine import RankedContextReport, RepositoryAstIndex, SymbolKind, SymbolRecord
from .context_engine import SUPPORTED_SOURCE_SUFFIXES
from .context import ContextWindow
from .evaluation import BenchmarkAblationReport, BenchmarkAblationRunner, BenchmarkAblationVariant
from .evaluation import BenchmarkReport, BenchmarkRunner, BenchmarkTaskSpec
from .evaluation import (
    GIT_DIFF_ARTIFACT_SCHEMA_VERSION,
    DEFAULT_SWEBENCH_DATASET_NAME,
    DEFAULT_SWEBENCH_SPLIT,
    SWEBENCH_ANNOTATED_REPORT_SCHEMA_VERSION,
    SWEBENCH_EXPERIMENT_SUMMARY_SCHEMA_VERSION,
    SWEBENCH_PREFLIGHT_SCHEMA_VERSION,
    SWEBENCH_PREDICTIONS_SCHEMA_VERSION,
    GitDiffReport,
    SWEbenchEvaluationResult,
    SWEbenchEvaluatorConfig,
    SWEbenchGitCommandResult,
    SWEbenchOfficialOutcome,
    SWEbenchPrediction,
    SWEbenchPredictionsArtifact,
    SWEbenchPreflightCheck,
    SWEbenchPreflightReport,
    SWEbenchTaskSpec,
    SWEbenchWorkspaceProvisioner,
    SWEbenchWorkspaceReport,
    annotate_benchmark_report_with_swebench_evaluation,
    build_swebench_experiment_summary,
    build_swebench_predictions_from_report,
    build_swebench_preflight_report,
    collect_git_diff,
    load_swebench_official_outcomes,
    load_swebench_tasks,
    render_swebench_experiment_summary_markdown,
    run_swebench_evaluation,
    write_git_diff_artifacts,
    write_swebench_experiment_summary,
    write_swebench_predictions_file,
    write_swebench_preflight_report,
    write_swebench_predictions_from_report,
)
from .models import AnthropicProvider, MockProvider, ModelProvider, ModelResponse
from .memory import MemoryExtractor, MemoryRecord, MemoryRetrievalReport, MemoryRetriever
from .memory import MemorySearchHit, MemoryStore, format_memory_prompt
from .patching import PatchOperation, PatchPolicy, PatchPolicyReport, PatchPolicySeverity
from .patching import PatchPolicyStatus, PatchPolicyViolation, PatchRollbackReport, PatchTransaction
from .patching import rollback_applied_patches
from .reflection import (
    FailureCategory,
    FailureReflectionReport,
    FailureReflector,
    FailureSignal,
    ReflectionRetryDecision,
    ReflectionRetryPolicy,
    ReflectionRetryStatus,
    RetryStrategyMatrix,
    RetryStrategyName,
    RetryStrategyPlan,
)
from .sandbox import DockerSandboxRunner, LocalSandboxRunner, SandboxCommandResult
from .sandbox import SandboxCommandStatus, SandboxSpec, WorkspaceSnapshot
from .sandbox import snapshot_workspace, write_sandbox_artifacts
from .security import CommandRisk, CommandRiskClassifier, WorkspacePathPolicy
from .storage import TrajectoryStore
from .verification import OutcomeVerifier, TaskConstraintEvaluation, TaskConstraintSpec
from .verification import TaskConstraintVerifier, VerificationReport, VerificationStatus
from .verification import StructuredTestResult, TestFramework, TestRunStatus, parse_test_output

__all__ = [
    "AgentLoop",
    "AgentState",
    "AnthropicProvider",
    "AstContextManager",
    "BenchmarkReport",
    "BenchmarkRunner",
    "BenchmarkTaskSpec",
    "BenchmarkAblationReport",
    "BenchmarkAblationRunner",
    "BenchmarkAblationVariant",
    "CommandRisk",
    "CommandRiskClassifier",
    "ContextCandidate",
    "ContextRanker",
    "ContextWindow",
    "DockerSandboxRunner",
    "FailureCategory",
    "FailureReflectionReport",
    "FailureReflector",
    "FailureSignal",
    "GitDiffReport",
    "GIT_DIFF_ARTIFACT_SCHEMA_VERSION",
    "DEFAULT_SWEBENCH_DATASET_NAME",
    "DEFAULT_SWEBENCH_SPLIT",
    "ReflectionRetryDecision",
    "ReflectionRetryPolicy",
    "ReflectionRetryStatus",
    "RetryStrategyMatrix",
    "RetryStrategyName",
    "RetryStrategyPlan",
    "MockProvider",
    "ModelProvider",
    "ModelResponse",
    "MemoryExtractor",
    "MemoryRecord",
    "MemoryRetrievalReport",
    "MemoryRetriever",
    "MemorySearchHit",
    "MemoryStore",
    "OutcomeVerifier",
    "PatchOperation",
    "PatchPolicy",
    "PatchPolicyReport",
    "PatchPolicySeverity",
    "PatchPolicyStatus",
    "PatchPolicyViolation",
    "PatchRollbackReport",
    "PatchTransaction",
    "PlanRepair",
    "PlanStepKind",
    "RunBudget",
    "RepositoryAstIndex",
    "RankedContextReport",
    "LocalSandboxRunner",
    "SandboxCommandResult",
    "SandboxCommandStatus",
    "SandboxSpec",
    "SWEbenchTaskSpec",
    "SWEBENCH_ANNOTATED_REPORT_SCHEMA_VERSION",
    "SWEBENCH_EXPERIMENT_SUMMARY_SCHEMA_VERSION",
    "SWEBENCH_PREFLIGHT_SCHEMA_VERSION",
    "SWEBENCH_PREDICTIONS_SCHEMA_VERSION",
    "SWEbenchEvaluationResult",
    "SWEbenchEvaluatorConfig",
    "SWEbenchGitCommandResult",
    "SWEbenchOfficialOutcome",
    "SWEbenchPrediction",
    "SWEbenchPredictionsArtifact",
    "SWEbenchPreflightCheck",
    "SWEbenchPreflightReport",
    "SWEbenchWorkspaceProvisioner",
    "SWEbenchWorkspaceReport",
    "WorkspaceSnapshot",
    "StructuredTestResult",
    "SUPPORTED_SOURCE_SUFFIXES",
    "SymbolKind",
    "SymbolRecord",
    "TaskStatus",
    "TaskConstraintEvaluation",
    "TaskConstraintSpec",
    "TaskConstraintVerifier",
    "TestFramework",
    "TestRunStatus",
    "ToolGuidanceCheck",
    "ToolGuidanceStatus",
    "ToolPlanningGuidance",
    "TrajectoryRecorder",
    "TrajectoryStore",
    "VerificationReport",
    "VerificationStatus",
    "WorkspacePathPolicy",
    "parse_test_output",
    "rollback_applied_patches",
    "snapshot_workspace",
    "write_sandbox_artifacts",
    "write_git_diff_artifacts",
    "write_swebench_experiment_summary",
    "write_swebench_predictions_file",
    "write_swebench_preflight_report",
    "write_swebench_predictions_from_report",
    "annotate_benchmark_report_with_swebench_evaluation",
    "build_plan_repair",
    "build_runtime_plan",
    "build_swebench_experiment_summary",
    "build_swebench_predictions_from_report",
    "build_swebench_preflight_report",
    "collect_git_diff",
    "format_memory_prompt",
    "load_swebench_tasks",
    "load_swebench_official_outcomes",
    "render_swebench_experiment_summary_markdown",
    "run_swebench_evaluation",
]
